name: Staging E2E Tests
run-name: Staging E2E Tests
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
jobs:
  Install-Required-Libs :
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
